server:
  port: 8082

#数据库配置
srping:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dsg
    username: dsg
    password: 123456

#mybatis 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.example.demo.common.pojo
  global-config:
    #刷新mapper
    db-config:
      #主键类型　０：“数据库ID自增”，１用户输入ID，２全局唯一ID（数字类型唯一ID），3全局唯一ID UUID；
      id-type: auto
      #字段策略 0：忽略判断  1：非NULL判断，2：非空判断
      field-strategy: not_null
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: postgre_sql
    sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false





